<a href="https://colab.research.google.com/github/Data-Intelligence-Mastery/data_science_interview_questions/blob/master/Q012_spiral_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Spiral matrix

`Python, Data Structures, Arrays, Matrix`

Given a matrix with `m` by `n` dimensions, print its elements in spiral form.

For example:

Given an array

col_0 | col_1 |col_2 | col_3
--- | --- | --- | ---
10 | 2 | 11 | 0
1 | 3 | 4 | 1
8 | 7 | 9 | 2
1 |3 | 2 | 4

Your function should return:

10, 2, 11, 0, 1, 2, 4, 2, 3, 1, 8, 1, 3, 4, 9, 7

With intuition, we should focus on getting the correct column and row index for each output because either column index (`j`) or row index (`i`) changes (increase or decrease) by 1 when moving from one item to next.

Let's write out the indexes of the spiral output. Whenever the output chagnes direction, we name a new sequence. Once we go through each line of data , we need to limit the range of index so that line of data won't be counted again. We call the range of row and column index: `i_min=0, i_max=4, j_min=0, j_max=4`.
We adapt Python's open bracket rule at the high end of range, so `i_max=4` is essentially `i_max=3`.

#### Sequence 0: [0, 0], [0, 1], [0, 2], [0, 3] 
Column index `j` increases by 1 till the max column index `j_max=4`. We just counted all first row (`i=0`), so we increase min row index `i_min` from 0 to 1 so the first row (`i=0`) won't be counted again later

#### Sequence 1: [1, 3], [2, 3], [3, 3] 
Continue from last index `[0, 3]`, row index `i` increases by 1 till the max row index `i_max=4`. Since we just counted all last column, so we decrease the max column index `j_max` by 1 from 4 to 3, so the last column won't be counted again later

#### Sequence 2: [3, 2], [3, 1], [3, 0]
Continue from last index `[3, 0]`, `j` decreases by 1 till `j_min=0`, decreases `i_max` by 1 to 3.

#### Sequence 3: [2, 0], [1, 0]
`i` decreases by 1 till `i_min=1', `j_min` increases by 1 to 1.

#### Sequence 4: [1, 1], [1, 2]
`j` increases by 1 till `j_max=3`, `i_min` increases by 1 to 2. Continue the same logic for the rest of the counting.

#### Sequence 5: [2, 2]

#### Sequence 6: [2, 1]

If you observe closely, you can see column and row indexes first increase then decrease then increase again. The direction of change (increase or decrease) cycles. Let's use `[1, -1]` to denote the direction of seeking new elements of the spiral (let's call the process *crawling*). 

Below is the code to find the spiral output of an array.



In [4]:
import numpy as np

a = [ [10, 2, 11, 0], [1, 3, 4, 1], [8, 7, 9, 2], [1, 3, 2, 4] ]
a = np.array(a)
m, n = a.shape
print('a = \n',a)
print('m, n = ', m, ',', n)

a = 
 [[10  2 11  0]
 [ 1  3  4  1]
 [ 8  7  9  2]
 [ 1  3  2  4]]
m, n =  4 , 4


In [5]:
# Solution

i_min, i_max = 0, m
j_min, j_max = 0, n

dir_ = [1, -1]
idx = (0,0) # Started at the first element
index = []

while len(index)< m*n:

    # Counting elements in each row
    while (dir_[0] > 0 and idx[1] < j_max) or (dir_[0] < 0 and idx[1]>= j_min):
        if idx not in index: index.append(idx)
        idx_ = idx 
        idx = (idx[0], idx[1]+dir_[0])

    i_max += -1 * (dir_[0] < 0) # update the max row index
    i_min += 1 * (dir_[0] > 0) # update the min row index
    idx = idx_ # to restore the last element that did meet the `while` criteria

    # Counting elements in each column
    while (dir_[0] > 0 and idx[0] < i_max) or (dir_[0] <0 and idx[0] >= i_min):
        if idx not in index: index.append(idx)
        idx_ = idx
        idx = (idx[0]+dir_[0], idx[1])

    j_max += -1 * (dir_[0] > 0) # update the max clumn index
    j_min += 1 * (dir_[0] <0) # update the min column index
    idx = idx_ # to restore the last element that did meet the `while` criteria

    dir_ = dir_[1:]+[dir_[0]] # update the direction of crawling

print('The index of the spiral output:\n', index)
spiral = [a[i,j] for (i,j) in index]
print ('Spiral output:\n', spiral)

The index of the spiral output:
 [(0, 0), (0, 1), (0, 2), (0, 3), (1, 3), (2, 3), (3, 3), (3, 2), (3, 1), (3, 0), (2, 0), (1, 0), (1, 1), (1, 2), (2, 2), (2, 1)]
Spiral output:
 [10, 2, 11, 0, 1, 2, 4, 2, 3, 1, 8, 1, 3, 4, 9, 7]
